#
# @copyright   Copyright (C) 2023 Combodo SARL
# @license     http://opensource.org/licenses/AGPL-3.0
#
# This playbook read the version of the REST/JSON API dedicated to Ansible
#
# Input parameters:
#  These are, by default, defined in the ./host_vars/localhost.yml file.
#  - itop_root = Root URL of the iTop application
#  - itop_ws_version = Web Service version
#  - itop_ws_auth_user = User login
#  - itop_ws_auth_pwd = User password
#
# Output parameters:
#  - None: result is displayed in standard output
#
---
- name: Get from iTop the version of the web services dedicated to Ansible 
  hosts: localhost 

  gather_facts: false

  vars:
    url: "{{ itop_root }}/webservices/rest.php?version={{ itop_ws_version }}"

# If you prefer to encrypt the login account and password in an Ansible vault:
#  - Uncomment the following 2 lines
#  - Store the parameter in a local itopvault.yml file
#  vars_files:
#    itopvault.yml

  tasks:
    - name: Call operation ansible/get_webservices_version 
      ansible.builtin.uri:
        url: "{{ url }}"
        method: POST
        force_basic_auth: true
        url_username: "{{ itop_ws_auth_user }}" 
        url_password: "{{ itop_ws_auth_pwd }}"
        body: json_data= {
          "operation":"ansible/get_webservices_version"
          }
        return_content: true
      register: response 

    - name: Save the Json data
      ansible.builtin.set_fact:
        jsondata: "{{ response.content | from_json }}"

    - name: Get error code, message and answer
      ansible.builtin.set_fact:
        error_code: "{{ jsondata | json_query('code') }}"
        message: "{{ jsondata | json_query('message') }}"

    - name: Display error, if any
      ansible.builtin.fail:
        msg: "{{ message }}"
      when: error_code != "0"

    - name: Display message
      ansible.builtin.debug:
        msg: "{{ message }}"
      when: error_code == "0"
