#
# @copyright   Copyright (C) 2023 Combodo SARL
# @license     http://opensource.org/licenses/AGPL-3.0
#
# This playbook builds an inventory list based on the information stored in iTop CMDB.
#
# Input parameters:
#  These are, by default, defined in the ./host_vars/localhost.yml file.
#  - itop_root = Root URL of the iTop application
#  - itop_ws_version = Web Service version
#  - itop_ws_auth_user = User login
#  - itop_ws_auth_pwd = User password
#  - itop_ws_ansible_uuid = UUID of the Ansible application in iTop
#  - itop_ws_ansible_inventory = Name of the inventory to consider
#  - itop_ws_ansible_oql_for_hosts = OQL that defines the list of hosts to consider
#  - itop_ws_ansible_attribute = Attribute of the hosts to be used in the output
#  - hosts_in_file = Boolean to define if the output should be stored in file or not
#  - local_inventory_path = Path to the output file, if any
#  - local_inventory_name = Name of the output file, if any
#
# Output parameters:
#  - file = File containing the list of hosts, if required.
#  - itop_hosts = List of hosts as a string
#
---
- name: Get from iTop a list of hosts defined by an OQL
  hosts: localhost

  vars:
    url: "{{ itop_root }}/webservices/rest.php?version={{ itop_ws_version }}"
    file: "{{ local_inventory_path }}/{{ local_inventory_name }}.txt"

# If you prefer to encrypt the login account and password in an Ansible vault:
#  - Uncomment the following 2 lines
#  - Store the parameter in a local itopvault.yml file
#  vars_files:
#    itopvault.yml

  tasks:
    - name: Check key variables are defined and not empty
      ansible.builtin.fail:
        msg: "One variable is empty"
      with_items:
        - "{{ itop_ws_ansible_uuid }}"
        - "{{ itop_ws_ansible_oql_for_hosts }}"
        - "{{ itop_ws_ansible_attribute }}"
      when:
        - not item
        - item is none

    - name: Call operation ansible/get_hosts_by_oql
      ansible.builtin.uri:
        url: "{{ url }}"
        method: POST
        force_basic_auth: true
        url_username: "{{ itop_ws_auth_user }}" 
        url_password: "{{ itop_ws_auth_pwd }}"
        body: json_data= {
          "operation":"ansible/get_hosts_by_oql",
          "uuid":"{{ itop_ws_ansible_uuid }}",
          "inventory":"{{ itop_ws_ansible_inventory }}",
          "oql":"{{ itop_ws_ansible_oql_for_hosts }}",
          "attribute":"{{ itop_ws_ansible_attribute }}"
          }
        return_content: true
      register: response 

    - name: Save the Json data
      ansible.builtin.set_fact:
        jsondata: "{{ response.content | from_json }}"

    - name: Get error code and message
      ansible.builtin.set_fact:
        error_code: "{{ jsondata | json_query('code') }}"
        message: "{{ jsondata | json_query('message') }}"

    - name: Display error, if any
      ansible.builtin.fail:
        msg: "{{ message }}"
      when: error_code != "0"

    - name: When operation is successfull
      block:
        - name: Get list of hosts
          ansible.builtin.set_fact:
            hosts_list: "{{ jsondata | json_query('objects.*.text_file') }}"

        - name: Save result in file
          ansible.builtin.copy:
            content: "{{ hosts_list[0] }}"
            dest: "{{ file }}"
          when: hosts_in_file == True

        - name: Save list in parameter
          ansible.builtin.set_fact:
            itop_hosts: "{{ hosts_list[0] }}"
      when: error_code == "0"
