#
# @copyright   Copyright (C) 2023 Combodo SARL
# @license     http://opensource.org/licenses/AGPL-3.0
#
# This task extracts parameters from a host file, transforms them into multiple csv lines and append them to a csv file.
#
# Input parameters:
#  - collect_condition: condition that should be met to process the hostfile
#  - csv_file: File where the relevant host attributes will be appended in a new line
#  - host_attributes: Array of Ansible attributes to lookup in the raw file, possibly in an array, and to add to the
#     csv output.
#  - out_of_array_attributes: Array of Ansible attributes to lookup in the raw file, at the first level of the json
#     structure, and to add to the csv output
#  - hostfile: The file containing the host's facts
#  - primary_key: Array containing Ansible attributes used to build the primary key, possibly in an array, and to add
#      to the csv output.
#  - out_of_array_primary_key: Array of Ansible attributes used to build the primary key that sit at the first level of
#     the json structure, and to add to the csv output
#
# Output parameters:
#  - Line appended to the csv_file with host attributes extracted from Ansible
#
---
- name: Create empty variables
  ansible.builtin.set_fact:
    primary_key_values: []
    out_of_array_primary_key_values: []
    attribute_values: []
    out_of_array_values: []

- name: Get primary key
  ansible.builtin.set_fact:
    primary_key_values: "{{ primary_key_values + [jsondata | community.general.json_query(list_name + primary_query)] }}"
  loop: "{{ primary_key }}"
  loop_control:
    loop_var: primary_query

- name: Get out of array primary key
  ansible.builtin.set_fact:
    out_of_array_primary_key_values: "{{ out_of_array_primary_key_values + [jsondata | community.general.json_query(out_of_array_primary_query)] }}"
  loop: "{{ out_of_array_primary_key }}"
  loop_control:
    loop_var: out_of_array_primary_query
  when : out_of_array_primary_key is defined

- name: Get host attributes
  ansible.builtin.set_fact:
    attribute_values: "{{ attribute_values + [jsondata | community.general.json_query(list_name + host_query)] }}"
  loop: "{{ host_attributes }}"
  loop_control:
    loop_var: host_query

- name: Get out of array attributes
  ansible.builtin.set_fact:
    out_of_array_values: "{{ out_of_array_values + [jsondata | community.general.json_query(out_of_array_query)] }}"
  loop: "{{ out_of_array_attributes }}"
  loop_control:
    loop_var: out_of_array_query
  when: out_of_array_attributes is defined

- name: Apppend result to output file with no out_of_array values
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ primary_key_values | join('_') }};{{ attribute_values | join(';') }}"
  when: ((out_of_array_primary_key is undefined) and (out_of_array_attributes is undefined))

- name: Apppend result to output file with out_of_array_atributes values (only)
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ primary_key_values | join('_') }};{{ attribute_values | join(';') }};{{ out_of_array_values | join(';') }}"
  when: ((out_of_array_primary_key is undefined) and (out_of_array_attributes is defined))

- name: Apppend result to output file with out_of_array_atributes values (only)
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ primary_key_values | join('_') }}_{{ out_of_array_primary_key_values | join('_') }};{{ attribute_values | join(';') }}"
  when: ((out_of_array_primary_key is defined) and (out_of_array_attributes is undefined))

- name: Apppend result to output file with out_of_array_atributes values (only)
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ primary_key_values | join('_') }}_{{ out_of_array_primary_key_values | join('_') }};{{ attribute_values | join(';') }};{{ out_of_array_values | join(';') }}"
  when: ((out_of_array_primary_key is defined) and (out_of_array_attributes is defined))

